import yfinance as yf
import pandas as pd

# Define the ticker symbol
tickerSymbol = 'AAPL'  # Example with Apple

# Get data from Yahoo Finance
data = yf.download(tickerSymbol, start='2020-01-01', end='2020-12-31')

# Calculate MACD
exp1 = data['Close'].ewm(span=12, adjust=False).mean()
exp2 = data['Close'].ewm(span=26, adjust=False).mean()
data['MACD'] = exp1 - exp2
data['Signal_Line'] = data['MACD'].ewm(span=9, adjust=False).mean()

# Calculate RSI
delta = data['Close'].diff(1)
gain = (delta.where(delta > 0, 0)).rolling(window=14).mean()
loss = (-delta.where(delta < 0, 0)).rolling(window=14).mean()
RS = gain / loss
data['RSI'] = 100 - (100 / (1 + RS))

# Calculate Bollinger Bands
data['Middle_Band'] = data['Close'].rolling(window=20).mean()
data['Upper_Band'] = data['Middle_Band'] + 1.96 * data['Close'].rolling(window=20).std()
data['Lower_Band'] = data['Middle_Band'] - 1.96 * data['Close'].rolling(window=20).std()

# Drop rows with NaN values generated by rolling windows
data.dropna(inplace=True)

# Save to CSV
data.to_csv('AAPL_stock_data_with_indicators.csv')

print("Data saved to 'AAPL_stock_data_with_indicators.csv'")
